redcarpet:
  extensions: ["superscript", "highlight"]
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false
description: {{ page.description }}
locale: ja_JP
